global using Brush = System.Windows.Media.Brush;
global using Brushes = System.Windows.Media.Brushes;
global using Button = System.Windows.Controls.Button;
global using System.IO;
global using Color = System.Windows.Media.Color;
global using Control = System.Windows.Controls.Control;
global using FontFamily = System.Windows.Media.FontFamily;
global using MessageBox = System.Windows.MessageBox;
global using MouseEventArgs = System.Windows.Input.MouseEventArgs;
global using Clipboard = System.Windows.Clipboard;
global using Pen = System.Windows.Media.Pen;
global using Point = System.Windows.Point;
global using RadioButton = System.Windows.Controls.RadioButton;
global using Size = System.Windows.Size;
